version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  tests:
    jobs:
      - node/test:
          version: '18.0'
      - node/test:
          version: '16.0'
      - node/test:
          version: '14.18'

