version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  tests:
    jobs:
      - node/test:
          version: '17.0'
      - node/test:
          version: '16.0'
      - node/test:
          version: '15.0'
      - node/test:
          version: '14.0'
      - node/test:
          version: '13.14'
      - node/test:
          version: '12.20'

